##########################################################################
##########################################################################
##                                                                      ##
##         _____ _   _____     _____     _   _____         _            ##
##        |     | |_|     |_ _| __  |___| |_|   __|___ ___| |_          ##
##        |  |  |   | | | | | | __ -| .'|   |  |  | . |_ -|   |         ##
##        |_____|_|_|_|_|_|_  |_____|__,|_|_|_____|___|___|_|_|         ##
##                        |___|                                         ##
##                                                                      ##
##          ..TV Show Library Collections YML Confg For..               ##
##         https://github.com/meisnate12/Plex-Meta-Manager              ##
##########################################################################
##                         github.com/ohmybahgosh                       ##
##########################################################################
##                   -=My Trakt.tv Collection Lists=-                   ##
##              _-=https://trakt.tv/users/hdlists/lists=-_              ##
##########################################################################
## Every Collection Comes With a Poster I Made & A Background I Grabbed ##
###  BY NO MEANS AM I A GRAPHIC DESIGNER, SO FEEL FREE TO SWAP POSTERS ###
##########################################################################


collections:
  Plex Popular:
    template: { name: Chart, num: 1 }
    tautulli_popular:
      list_days: 30
      list_size: 20
      list_buffer: 20
    tautulli_watched:
      list_days: 30
      list_size: 20
      list_buffer: 20
    summary: Shows Popular on Plex    
  Primetime:
    trakt_list:
      - https://trakt.tv/users/htlcalbbs/lists/primetime
  HBO:
    tmdb_network:
        - 49
        - 2593
        - 3186
        - 3308
  Cinemax:
    tmdb_network:
        - 359
  Showtime:
    tmdb_network:
        - 67
  Netflix:
    tmdb_network:
        - 213
  Hulu:
    tmdb_network:
        - 453
  Syfy:
    tmdb_network:
        - 77
        - 3701  
  Starz:
    tmdb_network:
        - 318
        - 758
        - 4906
  HGTV:
    tmdb_network:
        - 210
  TBS:
    tmdb_network:
        - 68
        - 160
        - 4888  
  National Geographic:
    tmdb_network:
        - 43
        - 799
        - 1756
        - 1825
        - 3355
        - 4293
        - 4476
  Prime Video:
    tmdb_network:
        - 1024
  YouTube:
    tmdb_network:
        - 247
        - 1436
        - 4869
  FX:
    tmdb_network:
        - 88
  Disney+:
    tmdb_network:
        - 2739
        - 2919
  Apple+:
    tmdb_network:
        - 2552
  Discovery:
    tmdb_network:
        - 10
        - 22
        - 64
        - 106
        - 244
        - 626
        - 670
        - 1079
        - 1287
        - 1534
        - 2087
        - 2480
        - 2692
        - 3045
        - 3591
        - 3900
        - 3953
        - 4440
        - 4462
        - 4741
  A&E:
    tmdb_network:
        - 129
        - 2639
        - 3688
  In Association With Marvel:
    template: {name: Show, show: "331980, 281662, 284190, 304219, 317953, 326490, 263365, 281485, 341455, 320558, 332027, 328552"}
    smart_label: year.asc
    sort_title: +2_1_In Association With Marvel
  Stargate:
    template: {name: Show, show: "72449, 70851, 83237, 339552"}
  What We Do in the Shadows:
    template: {name: Show, show: "358211, 344280"}
    smart_label: year.asc
    sort_title: +2_What We Do in the Shadows    
  Trending:
    smart_label: originally_available.desc
    sync_mode: sync
    trakt_trending: 40
    summary: Shows Trending across the internet

  Popular:
    smart_label: originally_available.desc
    sync_mode: sync
    imdb_list:
      url: https://www.imdb.com/search/title/?title_type=tv_series,tv_miniseries
      limit: 40
    summary: Popular Shows across the internet
  Home Renovations:
    smart_label: originally_available.desc
    sync_mode: sync
    imdb_list:
      url: https://www.imdb.com/search/title/?title_type=tv_series&keywords=renovation&languages=en&adult=include
      limit: 40
    summary: Renovation TV Shows

  Apple Original Series 2021-2025:
    smart_label: originally_available.desc
    sync_mode: sync
    sort_title: +++++++++++++++++++++_1APPLE
    imdb_list:
      url:   https://www.imdb.com/search/title/?title_type=feature,tv_movie,tv_series,tv_special,tv_miniseries,documentary,video,tv_short&release_date=2021-01-01,2025-12-31&genres=!animation&countries=us&languages=en&sort=release_date,desc&count=250&companies=co0546168
    summary: All Apple TV Original Series/Shows From 2021-2025
    url_poster: https://i.imgur.com/O9iWork.png
    url_background: https://wallpaper-house.com/data/out/8/wallpaper2you_228774.png
    sonarr_add: false
    sonarr_search: true
    sonarr_monitor: none

  Amazon Original Series 2021-2025:
    smart_label: originally_available.desc
    sync_mode: sync
    sort_title: +++++++++++++++++++++_1APPLE
    imdb_list:
      url:   https://www.imdb.com/search/title/?title_type=feature,tv_movie,tv_series,tv_special,tv_miniseries,documentary,video,tv_short&release_date=2021-01-01,2025-12-31&genres=!animation&countries=us&languages=en&sort=release_date,desc&count=250&companies=co0319272
    summary: All Apple TV Original Series/Shows From 2021-2025
    url_poster: https://i.imgur.com/nU3gqqB.png
    url_background: https://i.imgur.com/2jfs7oS.png
    sonarr_add: false
    sonarr_search: true
    sonarr_monitor: none

  Netflix Original Series 2021-2025:
    smart_label: originally_available.desc
    sync_mode: sync
    sort_title: +++++++++++++++++++++_1Netflix
    imdb_list:
      url: https://www.imdb.com/search/title/?title_type=feature,tv_movie,tv_series,tv_special,tv_miniseries,documentary,video,tv_short&release_date=2021-01-01,2025-12-31&genres=!animation&countries=us&languages=en&sort=release_date,desc&count=250&companies=co0144901
    summary: All Netflix Original Series/Shows From 2021-2025
    url_poster: https://i.imgur.com/7kiE1MU.png
    url_background: https://img5.goodfon.com/original/1920x1080/1/61/fon-netflix-logo-raduga-tsvet-fon-background-skachat-oboi-sk.jpg
    sonarr_add: false
    sonarr_search: true
    sonarr_monitor: none

  HBO Max Original Series 2021-2025:
    smart_label: originally_available.desc
    sync_mode: sync
    sort_title: +++++++++++++++++++++_1HBOMAX
    imdb_list:
      url: https://www.imdb.com/search/title/?title_type=feature,tv_movie,tv_series,tv_special,tv_miniseries,documentary,video,tv_short&release_date=2021-01-01,2025-12-31&genres=!animation&countries=us&languages=en&sort=release_date,desc&count=250&companies=co0754095
    summary: All HBO Max Series/Shows From 2021-2025
    url_poster: https://i.redd.it/zxdvw3tk3f151.jpg
    url_background: https://wallpapercave.com/wp/wp6402755.png
    sonarr_add: false
    sonarr_search: true
    sonarr_monitor: none

  HULU Original Series 2021-2025:
    smart_label: originally_available.desc
    sync_mode: sync
    sort_title: +++++++++++++++++++++_1HULU
    imdb_list:
      url: https://www.imdb.com/search/title/?title_type=feature,tv_movie,tv_series,tv_special,tv_miniseries,documentary,video,tv_short&release_date=2021-01-01,2025-12-31&genres=!animation&countries=us&languages=en&sort=release_date,desc&count=250&companies=co0218858
    summary: All HULU Original Series/Shows From 2021-2025
    url_poster: https://plexcollectionposters.com/images/2019/05/26/Hulu6ddad752a5ce9bac.jpg
    url_background: https://cdn.vox-cdn.com/thumbor/oR4hqrmTxbX_O4gdJ6np8h-PxFk=/0x439:750x861/1600x900/cdn.vox-cdn.com/uploads/chorus_image/image/56311701/Image_uploaded_from_iOS__8_.1503433270.jpg
    sonarr_add: false
    sonarr_search: true
    sonarr_monitor: none
  


