###########################################################
#                  Star Wars Movies                       #
# You can never have too many 'Star Wars' collections     #
#  A few collections of SW movies, and metadata edits     #
#                   By: twhiting9275                      #
###########################################################
templates:
  Collection:
    optional:
      - collection
      - movie
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<movie>>
    sync_mode: sync

collections:
  "Star Wars: by year" :
    template: {name: Collection, collection: 10}
    collection_order: release
  "Star Wars: by timeline":
    template: {name: Collection, movie: "1893, 1894, 12180, 1895, 11, 1891, 1892, 140607, 181808, 181812"}
    summary: This is a collection of main star wars movies, plus The Clone Wars animated movie, arranged by when events took place   
    collection_order: alpha
  "Star Wars: Stories":
    template: {name: Collection, movie: "348350 , 330459" }        
    summary: Collection of Star Wars stories, outside of the Skywalker Saga    
    collection_order: release
  "Star Wars: The Rian Johnson Trilogy":
    template: {name: Collection, collection: 820683}        
    collection_order: release    
  "Star Wars: The Ewok Advenures":
    template: {name: Collection, collection: 133830}        
    collection_order: release    
  "Star Wars: The Original Trilogy":
    template: {name: Collection, movie: "11, 1891, 1892"}
    summary: The trilogy that started it all! George Lucas' original Star Wars , episodes 4-6
    collection_order: release    
  "Star Wars: The Prequel Trilogy":
    template: {name: Collection, movie: "1893, 1894, 1895"}
    summary: The prequel trilogy, episodes 1-3
    collection_order: release    
  "Star Wars: The Disney Trilogy":
    template: {name: Collection, movie: "140607, 181808, 181812"}
    summary: The Disney Star Wars trilogy
    collection_order: release     
  "Star Wars: Behind the Scenes":
    summary: Some cool videos , interviews and the like about one of the biggest movie franchises in the world    
    collection_order: release
    template: {name: Collection, movie: "825647, 435365, 72694, 128295, 81418, 154452, 376798, 372906, 277499, 507052, 486000, 363132, 659114, 786611, 485994, 485997, 729605, 219566, 372909, 515580, 76180"}

metadata:
  
  "Star Wars: Episode I - The Phantom Menace":
    sort_title: Star Wars 1
  "Star Wars: Episode II - Attack of the Clones":
    sort_title: Star wars 2
  "Star Wars: The Clone Wars":
    sort_title: Star Wars 3
  "Star Wars: Episode III - Revenge of the Sith":
    sort_title: Star Wars 4
  Star Wars:
    sort_title: Star Wars 5
  The Empire Strikes Back:
    sort_title: Star Wars 6    
  Return of the Jedi:
    sort_title: Star Wars 7    
  "Star Wars: The Force Awakens":    
    sort_title: Star Wars 8
  "Star Wars: The Last Jedi":    
    sort_title: Star Wars 9
  "Star Wars: The Rise of Skywalker":
    sort_title: Star Wars 10
